version: 3.0.{build}
image: Visual Studio 2019
skip_tags: true
configuration:
- Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: .\prebuild.ps1
- cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: 5mSnG9xdZ10yKDFhtI0w8p6aaj0m5ULQvVwlSGuzR2/D6LjQftisSQo3J6DYvZfw
  skip_symbols: false
  artifact: /.*\.nupkg/
- provider: GitHub
  release: Lorem-Universal-NET-v$(appveyor_build_version)
  description: $(appveyor_repo_commit_message)
  auth_token:
    secure: jtEqWpP0mI7h+Bapo8DhdJDSQxUV60pDwfQqLdFZqpHV4LqcCEmrcTmNMf6pu9bl
  artifact: /.*\.nupkg/
  draft: false
  prerelease: false
  on:
    branch: master
- provider: GitHub
  release: Lorem-Universal-NET-v$(appveyor_build_version)-beta
  description: $(appveyor_repo_commit_message)
  auth_token:
    secure: jtEqWpP0mI7h+Bapo8DhdJDSQxUV60pDwfQqLdFZqpHV4LqcCEmrcTmNMf6pu9bl
  artifact: /.*\.nupkg/
  draft: false
  prerelease: true
  on:
    branch: dev