version: 4.0.{build}
image: Visual Studio 2019
skip_tags: true
configuration:
- Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: .\prebuild.ps1
- cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: 6iDwjn2nT7lbeEqrDcnkxGbFgQo5A5KNtakatRdgwXS0RWKTCrCdZp/FLEqcXTim
  skip_symbols: false
  artifact: /.*\.nupkg/
- provider: GitHub
  release: Lorem-Universal-NET-v$(appveyor_build_version)
  description: $(appveyor_repo_commit_message)
  auth_token:
    secure: B6smjWT15M4dSVKe+bbWP4aZ/sno0gEKqS9sow6ugbMWBx/q/qeJrmPQuJFH4qvi
  artifact: /.*\.nupkg/
  draft: false
  prerelease: false
  on:
    branch: master
- provider: GitHub
  release: Lorem-Universal-NET-v$(appveyor_build_version)-beta
  description: $(appveyor_repo_commit_message)
  auth_token:
    secure: B6smjWT15M4dSVKe+bbWP4aZ/sno0gEKqS9sow6ugbMWBx/q/qeJrmPQuJFH4qvi
  artifact: /.*\.nupkg/
  draft: false
  prerelease: true
  on:
    branch: dev