version: 4.0.{build}
image: Visual Studio 2019
skip_tags: true
configuration:
- Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '4.0.0'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
- path: '**\*.snupkg'
deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: rqiuU99+N0SgoiauA3nzo1iwyM765dRoGY8twPzMiILm95ZeQXjPr3HO81BvmSv7
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
- provider: GitHub
  release: Lorem-Universal-NET-v$(appveyor_build_version)
  description: $(appveyor_repo_commit_message)
  auth_token:
    secure: B6smjWT15M4dSVKe+bbWP4aZ/sno0gEKqS9sow6ugbMWBx/q/qeJrmPQuJFH4qvi
  artifact: /.*(\.|\.s)nupkg/
  draft: false
  prerelease: false
  on:
    branch: master
- provider: GitHub
  release: Lorem-Universal-NET-v$(appveyor_build_version)-beta
  description: $(appveyor_repo_commit_message)
  auth_token:
    secure: B6smjWT15M4dSVKe+bbWP4aZ/sno0gEKqS9sow6ugbMWBx/q/qeJrmPQuJFH4qvi
  artifact: /.*(\.|\.s)nupkg/
  draft: false
  prerelease: true
  on:
    branch: dev